version: '3.8'
services:
  create:
    build:
      context: ./
      dockerfile: create.dockerfile
    container_name: create
    working_dir: /app
    volumes:
      - ./app:/app
    command: /bin/sh

  react:
    build:
      context: ./
      dockerfile: react.dockerfile
    container_name: react
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app:cached
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true
    stdin_open: true
    command: yarn start

  firebase:
    build:
      context: ./
      dockerfile: firebase.dockerfile
    container_name: firebase
    ports:
      - 5000:5000
      - 9005:9005
    working_dir: /app
    volumes:
      - ./app:/app:cached
    tty: true
    stdin_open: true
    command: /bin/sh
volumes:
  node_modules: {}
  yarn-cache: {}
