version: '3.8'
services:
  react:
    build:
      context: ./
      dockerfile: react.dockerfile
    container_name: react
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    command: yarn start
    # 初回のみ command: ash -c 'npx create-react-app . --template typescript && yarn add firebase'

  firebase:
    build:
      context: ./
      dockerfile: firebase.dockerfile
    container_name: firebase
    ports:
      - 5000:5000
      - 9005:9005
    working_dir: /app
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    command: /bin/sh
